# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: My Jekyll-Git Site!
email: meteorlando@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is AWESOME! I think -- i'm trying to see how its different than Wordpress but I will in time.  
  I just uploaded this from el Terminal with Jekyll! well..code academys local host :->
  
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: orlandopetography
github_username:  ooberoo22

# Build settings
markdown: kramdown
